In [89]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
b_ds = load_boston()

In [27]:
# data: contains the information for various houses
# target: prices of the house
# feature_names: names of the features
# DESCR: describes the dataset

In [134]:
print(b_ds.data.shape)
print('\n')

print(b_ds.target.shape)
print('\n')

print(b_ds.feature_names)


(506, 13)


(506,)


['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [135]:
x = pd.DataFrame(boston.data, columns = boston.feature_names)
y = pd.DataFrame(b_ds.target)

# print(x),(y)
# x.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [217]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

lr = LinearRegression()
lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

y_pred[:5]

array([[28.99672362],
       [36.02556534],
       [14.81694405],
       [25.03197915],
       [18.76987992]])

In [153]:
lr.coef_

array([[-1.13055924e-01,  3.01104641e-02,  4.03807204e-02,
         2.78443820e+00, -1.72026334e+01,  4.43883520e+00,
        -6.29636221e-03, -1.44786537e+00,  2.62429736e-01,
        -1.06467863e-02, -9.15456240e-01,  1.23513347e-02,
        -5.08571424e-01]])

In [272]:
y_pred = lr.predict(X_test)
x_train_pred = lr.predict(X_train)
y_pred[:5]

array([[28.99672362],
       [36.02556534],
       [14.81694405],
       [25.03197915],
       [18.76987992]])

In [230]:
y_test
# X_test.shape

0
173  23.6
274  32.4
491  13.6
72   22.8
452  16.1
..    ...
412  17.9
436   9.6
411  17.2
86   22.5
75   21.4

[102 rows x 1 columns]

In [237]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.6687594935356329

In [267]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

24.291119474973456

In [282]:
import matplotlib.pyplot as plt

plt.scatter(y_train, x_train_pred)
plt.xlabel("the actual prices")
plt.ylabel("the predicted prices")
plt.title("House price prediction in boston city")
plt.legend(['pred'], loc='upper right')
plt.show()
